### ISSUE TITLE
DeadLock Handler issue

### ISSUE THREAD

**Issue by davejefferies** [happilymarrieddad/mysql-clusterfarm#1]
The DeadLockHandler isn't working.  when I set useDeadlockHandling to true in the config as per the example I get an error 'TypeError: callback is not a function'.  When I set useDeadlockHandling I have no issues.

**Comment by happilymarrieddad** [comment]
@davejefferies Can you please post your code? I'm having trouble seeing where this can happen. I've added logic to verify the func is set and my tests are not showing what you are saying. Thanks!
